name: Code Complexity & CFG Analysis

on:
  push:
    branches:
      - main
      - test # Run on pushes to main or test branches
  pull_request:
    branches:
      - main
      - test # Run on pull requests targeting main or test

jobs:
  analyze:
    runs-on: ubuntu-latest # Use an Ubuntu runner, as it simplifies Graphviz installation

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to get your repository's code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up a Python environment
      with:
        python-version: '3.x' # Use the latest Python 3.x version available

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radon graphviz astunparse

    - name: Install Graphviz (system-wide)
      # Graphviz is still needed system-wide for the 'graphviz' Python library to function
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Run Code Analysis Script and Generate CFG & PNG
      id: run_analysis
      run: |
        echo "Running Python script..."
        python generate_ast_cfg.py

        echo "Listing files in current directory after script execution:"
        ls -l

        # The Python script now generates both .dot and .png directly.
        # We'll just check for the .png to confirm success.
        if [ -f user_behavior_cfg_ast.png ]; then
          echo "Generated user_behavior_cfg_ast.png successfully."
        else
          echo "Error: user_behavior_cfg_ast.png was NOT found. CFG image could not be generated by Python script."
          exit 1 # Fail the step if the .png file is missing
        fi

    - name: Upload CFG Artifacts
      uses: actions/upload-artifact@v4 # Action to upload generated files as workflow artifacts
      with:
        name: code-analysis-results # Name of the artifact bundle
        path: |
          user_behavior_cfg_ast.dot  # Upload the .dot file
          user_behavior_cfg_ast.png  # Upload the generated PNG image
        retention-days: 5

    - name: Display Completion Message
      run: echo "Code complexity and CFG analysis complete. Check workflow logs for complexity value and download 'code-analysis-results' artifact for CFG."
